#!/usr/bin/env bash
#transfers a file from our client to a server
path_file = $1
ip = $2
username = $3
path_ssh = $4
if ["$# -lt 3"] 
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$path_ssh" -o StrictHostKeyChecking=no "$path_file" "$username"@"$ip":~/