#!/usr/bin/env bash
# Installing Nginx on Server
sudo apt-get update -y
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R ubuntu:ubuntu /var/www
echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
